package pmf.math.konstante;

public enum ImenaKalkulatora {
  CEZAROVA_SIFRA,
  SUPSTITUCIJSKA_SIFRA,
  AFINA_SIFRA,
  HILLOVA_SIFRA,
  VIGENEROVA_SIFRA,
  PLAYFAIROVA_SIFRA,
  STUPCANA_TRANSPOZICIJA,
  RSA_SIFRA,
  EL_GAMALOVA_SIFRA,
  ANALIZA_TEKSTA,
  UVODNA_STRANICA
}
