/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pmf_math_algoritmi_TeorijaBrojeva */

#ifndef _Included_pmf_math_algoritmi_TeorijaBrojeva
#define _Included_pmf_math_algoritmi_TeorijaBrojeva
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pmf_math_algoritmi_TeorijaBrojeva
 * Method:    prost
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_pmf_math_algoritmi_TeorijaBrojeva_prost
  (JNIEnv *, jclass, jlong);

/*
 * Class:     pmf_math_algoritmi_TeorijaBrojeva
 * Method:    modularnoPotenciranje
 * Signature: (JJJ)I
 */
JNIEXPORT jlong JNICALL Java_pmf_math_algoritmi_TeorijaBrojeva_modularnoPotenciranje
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
